# Generated by Django 3.2.8 on 2021-10-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('user_id', models.CharField(max_length=18)),
                ('prev_pwd', models.CharField(max_length=18)),
                ('new_pwd', models.CharField(max_length=18)),
            ],
        ),
    ]
