# Generated by Django 3.2.8 on 2021-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=18)),
                ('prev_pwd', models.CharField(max_length=18)),
                ('receive_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
