# Generated by Django 3.2.8 on 2021-11-03 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(default='2021-11-03 13:37:28')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='receive_date',
        ),
        migrations.AddField(
            model_name='account',
            name='create_date',
            field=models.DateTimeField(default='2021-11-03 13:37:28'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoadmin.question')),
            ],
        ),
    ]
