# Generated by Django 3.2.8 on 2021-11-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoadmin', '0003_auto_20211103_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_date',
            field=models.DateTimeField(default='2021-11-03 13:41:58'),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(default='2021-11-03 13:41:58'),
        ),
    ]
