# Generated by Django 3.2.8 on 2021-11-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoadmin', '0004_auto_20211103_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_date',
            field=models.DateTimeField(default='2021-11-03 14:39:26'),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(default='2021-11-03 14:39:26'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
